name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            is_clang: false
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            is_clang: true

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y gn ninja-build libssl-dev

    - name: Setup project dependencies
      run: git submodule update --init

    - name: Configure GN
      run: gn gen out/build --args="is_debug=false is_clang=${{ matrix.is_clang }} cc=\"${{ matrix.c_compiler }}\" cxx=\"${{ matrix.cpp_compiler }}\""

    - name: Build
      run: ninja -C out/build tests

    - name: Test
      working-directory: out/build
      run: ctest
